### PR TITLE
fix: handle dust and gas sensor interactions

### LINKED ISSUE #3136: Certain elements do nothing when clicked
**Describe the bug**
Certain elements do nothing when clicked, as options in Multimeter, or directly the dust sensor and the gas sensor

**Expected Behavior**
Navigation or toggle menu

**Steps to reproduce it**
Click on them

**Screenshots of the issue**

https://github.com/user-attachments/assets/408feea3-d8a1-4c90-b586-b5b673a61e44

**System Information**
<table>
<tr>
  <td>Platform</td><td>Android</td>
</tr>
<tr>
  <td>Device</td><td>Pixel 9A</td>
</tr>
<tr>
  <td>OS Version</td><td>Android 16</td>
</tr>
</table>

**Would you like to work on the issue?**
Yes, I see that, for example, in multimeter it's just a check:
```Dart
onOptionsPressed:
                    provider.isPlayingBack ? null : _showOptionsMenu,
```
So in my case is null, but could be better hide this parameter if not in playing or just to explain what do you need to start dust sensor

### PR DESCRIPTION
**Pull request by Irfan-del-droid**
Hi, I reviewed PR #3142 and noticed it seems to focus mainly on the Multimeter interaction and the web USB flow. I’m interested in contributing to the remaining parts of #3136, especially the Dust Sensor and Gas Sensor interactions.
A focused PR for the remaining Dust/Gas sensor issues, or. a follow-up PR covering the full remaining scope of #3136.

🐛 Issue Fixed
Resolves #3136 - Gas Sensor and Dust Sensor menu items were not clickable/visible

📋 Changes
- ✅ Created placeholder screens for Gas Sensor and Dust Sensor
- ✅ Enabled both sensors in the instruments menu
- ✅ Added proper routing and navigation
- ✅ Shows clear user feedback explaining feature status
- ✅ Follows existing code patterns and conventions

 🎯 UX Improvements
Every clickable UI element now either:
- Performs an action, OR
- Navigates to a screen, OR  
- Shows feedback explaining why it cannot proceed

No element silently does nothing.

📁 Files Changed
1. `lib/view/gas_sensor_screen.dart` (NEW) - Gas Sensor placeholder
2. `lib/view/dust_sensor_screen.dart` (NEW) - Dust Sensor placeholder  
3. `lib/view/instruments_screen.dart` - Uncommented sensor entries
4. `lib/main.dart` - Added routes

✨ Key Features
- Clean, minimal implementation
- No conflicts with PR #3142 (multimeter changes)
- Doesn't touch Web USB logic or provider architecture
- Production-ready, null-safe code
- Consistent with existing app design
- Uses existing localization strings
- Proper orientation handling

🧪 Testing
- Verified navigation works correctly
- Checked UI renders properly
- Confirmed no compilation errors

### CODE REVIEW

**Comment by Irfan-del-droid** [comment]
The RCE warnings are pre-existing security advisories in the base repository,
check it out.

**Comment by rahul31124** [comment]
Closing in favour of #3244
